### ISSUE TITLE
Seeking clarification on one-sided p-value from the permutation test

### ISSUE THREAD

**Issue by haoyusimon** [ryansteed/ieat#2]
Hi Authors,

Thank you so much for the great work! After reading the paper, I have a question regarding the permutation test that tests the significance of the differential association 𝑠(𝑋, 𝑌, 𝐴, 𝐵). I noticed that in both WEAT and IEAT, the one-sided p-value is calculated as 𝑃𝑟[𝑠(𝑋𝑖, 𝑌𝑖, 𝐴, 𝐵) > 𝑠(𝑋, 𝑌, 𝐴, 𝐵)], with the null hypothesis that the differential association should be 0. However, since this is a one-tailed test, does this assume that the alternative hypothesis is "the differential association is **larger than** 0"? But I am wondering why the alternative hypothesis is not "the differential association is **not equal to** 0"? Because the differential association can be in either direction, positive or negative, (if I understand correctly), and only testing the bias in the positive direction may not be complete. May I know the reason that a two-sided test is not used? Thank you!

**Comment by ryansteed** [comment]
Thanks for your question! Your understanding is correct — the differential association can be negative, but we are interested in testing only the hypothesis that the differential association is positive. In our paper (and in the original WEAT paper) the goal is to see whether word/image embeddings exhibit a particular direction of stereotypical association (e.g. “White” associated with tools, “Black” associated with weapons, rather than vice versa) almost always the same direction of association as previous tests from psychology. So, we know a priori which direction we are interested in, set X, Y, A, and B accordingly, and use a one-sided test.

If you were interested in testing for bias in either direction of association (e.g., in the exploratory case where you don’t have a strong prior), you could also use the two-sided test. However, in this case, significance correlates with the effect size, so it may not add much.

**Comment by haoyusimon** [comment]
Hi Ryan, 

Thank you so much for the reply! Now I understand the rationale for using the one-sided test. I also noticed that in your presentation slides for FAccT 2021, slide 8, for those significant effects (p < 0.1), the skin-tone test on SimCLRv2 has a negative effect size. May I know how to interpret this result? Because it seems that there is a contradiction: the skin-tone test on SimCLRv2 has a p-value < 0.1 in the one-sided test, suggesting that the SimCLRv2 has a **positive** direction of differential association for skin tones. However, the effect size is negative, suggesting that the SimCLRv2 has a **negative** direction of differential association for skin tones. In this case, the insights from p-value and effect size seem to contradict each other. May I seek your clarification on this? Thank you!

<img width="1008" alt="image" src="https://github.com/ryansteed/ieat/assets/77672961/c506d696-efff-4482-9e1c-3a489c6b38f1">

**Comment by ryansteed** [comment]
The figure is a bit confusing without the full caption, apologies — in fact, the effect size for the Skin-Tone iEAT using SimCLR was *not* significant. In those diagrams, only points with a solid fill are significant at  $p < 0.1$. The left side of the screen shows tests for which at least one of the models has as a significant effect size — in this case, iGPT.

You can find the full list of p-values in the [paper](https://dl.acm.org/doi/10.1145/3442188.3445932) (Table 1). For SimCLR x Skin Tone, $p = 0.71$. You should find that all the negative effect sizes have large p-values.

**Comment by haoyusimon** [comment]
I see, thank you so much for the detailed explanations!
